if (import.meta.env.DEV) {
	window.Config = {
		VITE_API_URL: `{VITE_API_URL}`,
		VITE_CLIENT_BASE_URL: `{VITE_CLIENT_BASE_URL}`,
		VITE_IDENTITY_AUTH_URL: `{VITE_IDENTITY_AUTH_URL}`,

		VITE_IDENTITY_ISSUER: `{VITE_IDENTITY_ISSUER}`,
		VITE_IDENTITY_CLIENT_ID: `{VITE_IDENTITY_CLIENT_ID}`
	};
}
